default: &default
  source_path: app/javascript
  public_output_path: packs
  cache_path: tmp/cache/shakapacker
  compile: true
  compiler_strategy: mtime

development:
  <<: *default
  # Serve precompiled assets instead of using dev server (no need to run dev server)
  dev_server: false
  # If you want to enable dev server later, use:
  # dev_server:
  #   server: 'http'
  #   host: localhost
  #   port: 3035
  #   public: localhost:3035
  #   hmr: false
  #   inline_css: true
  #   client:
  #     overlay: true
  #     webSocketURL:
  #       hostname: '0.0.0.0'
  #       pathname: '/ws'
  #       port: 8080

test:
  <<: *default
  dev_server: false
  compile: true
  compiler_strategy: mtime

production:
  <<: *default
  compile: false
  dev_server: false
